numst(range(1,11))
print('The first three items in the list are:')
print(nums[:3])
print('Three items from the middle of the list are:')
print(nums[int(len(nums)/2):])
print('The last three items in the list are:')
print(nums[-3:])
